const BOARD_SIZE = 800;
const RANKS = 8;
const FILES = RANKS;
const SQUARE_SIZE = BOARD_SIZE / RANKS;
const BOARD_BORDER_STROKE_WIDTH = 4;
const BOARD_BORDER_WIDTH = SQUARE_SIZE / 2;
const BOARD_BORDER_HEIGHT = BOARD_BORDER_WIDTH;
const BOARD_OFFSET = BOARD_BORDER_STROKE_WIDTH + BOARD_BORDER_WIDTH;

const TOTAL_BOARD_SIZE = BOARD_SIZE + BOARD_OFFSET * 2;

const COLORS = {
    DEBUG: '#C529D3',
    BUTTON_HOVER: '#B9B9B9',
    LIGHTER: '#EEE',
    LIGHT: '#D9D9D9',
    DARK: '#343441',
    DARKER: '#222',
    MOVES: {
        CURRENT: '#F9F277B8',
        EMPTY: '#6D7ED0B8',
        TAKE_PIECE: '#5A9367B8',
        ENEMY: 'rgba(203,43,43,0.72)',
    },
    INFO_PANEL: {
        BACKGROUND: '#484855',
    },
};

export {
    BOARD_SIZE,
    RANKS,
    FILES,
    SQUARE_SIZE,
    BOARD_BORDER_STROKE_WIDTH,
    BOARD_BORDER_HEIGHT,
    BOARD_BORDER_WIDTH,
    BOARD_OFFSET,
    TOTAL_BOARD_SIZE,
    COLORS,
};
