const INFO_PANEL_DIVIDER_LEFT_WIDTH = 1;
const INFO_PANEL_DIVIDER_WIDTH = INFO_PANEL_DIVIDER_LEFT_WIDTH + 1;
const INFO_PANEL_WIDTH = 400 + INFO_PANEL_DIVIDER_WIDTH;

export { INFO_PANEL_WIDTH, INFO_PANEL_DIVIDER_LEFT_WIDTH, INFO_PANEL_DIVIDER_WIDTH };
